name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      
      - name: Install poetry
        run: python3 -m pip install build poetry --user

      - name: Install dependencies
        run: poetry install --no-root

      - name: Check formatting
        run: |
          poetry run ruff check .
          poetry run black --check .

      - name: Test the build 
        run: poetry build
