
name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Install pypa/build
        run: python3 -m pip install build poetry --user

      - name: Test the build 
        run: python3 -m build
